position_in_class: before
position_in_test: before
position_in_fixture: before
position_in_factory: before
position_in_serializer: before
show_foreign_keys: true
show_complete_foreign_keys: false
show_indexes: true
simple_indexes: false
model_dir: app/models
include_version: false
exclude_tests: true
exclude_fixtures: true
exclude_factories: true
exclude_serializers: true
exclude_scaffolds: true
exclude_controllers: true
exclude_helpers: true
exclude_sti_subclasses: false
ignore_model_sub_dir: false
hide_limit_column_types: integer,bigint,boolean
hide_default_column_types: json,jsonb,hstore
format_bare: true
format_rdoc: false
format_yard: false
format_markdown: false
sort: false
force: false
frozen: false
classified_sort: true
with_comment: true
