# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

style = Style.create(name: "Wing Chun")
pole_style = Style.create(name: "Six and a half point long pole")
ng_mui = Practitioner.create(name: "Ng Mui", legendary: true, controversial: true)
chi_sin = Practitioner.create(name: "Chi Sin", legendary: true, controversial: true)
yim_wing_chun = Practitioner.create(name: "Yim Wing Chun", controversial: true)
yim_wing_chun.disciple_of!(ng_mui, style: style)
leung_bok_cho = Practitioner.create(name: "Leung Bok Cho")
leung_bok_cho.disciple_of!(yim_wing_chun, style: style)
leung_lan_kwai = Practitioner.create(name: "Leung Lan Kwai")
leung_lan_kwai.disciple_of!(leung_bok_cho, style: style)
leung_yee_tai = Practitioner.create(name: "Leung Yee Tai")
leung_yee_tai.disciple_of!(chi_sin, style: pole_style)
wong_wah_po = Practitioner.create(name: "Wong Wah Po")
leung_yee_tai.disciple_of!(wong_wah_po, style: style)
wong_wah_po.disciple_of!(leung_yee_tai, style: pole_style)
wong_wah_po.disciple_of!(leung_lan_kwai, style: style)
leung_jan = Practitioner.create(name: "Leung Jan")
leung_jan.disciple_of!(leung_yee_tai, style: style)
leung_jan.disciple_of!(wong_wah_po, style: style)
chan_wah_shun = Practitioner.create(name: "Chan Wah Shun")
chan_wah_shun.disciple_of!(leung_jan, style: style)
leung_bik = Practitioner.create(name: "Leung Bik")
leung_bik.disciple_of!(leung_jan, style: style)
leung_bik.disciple_of!(wong_wah_po, style: style)
yip_man = Practitioner.create(name: "Yip Man")
yip_man.disciple_of!(chan_wah_shun, style: style)
yip_man.disciple_of!(leung_bik, style: style)
yip_chun = Practitioner.create(name: "Yip Chun")
yip_chun.disciple_of!(yip_man, style: style)
yip_ching = Practitioner.create(name: "Yip Ching")
yip_ching.disciple_of!(yip_man, style: style)
leung_sheung = Practitioner.create(name: "Leung Sheung")
leung_sheung.disciple_of!(yip_man, style: style)
chu_shong_tin = Practitioner.create(name: "Chu Shong Tin")
chu_shong_tin.disciple_of!(yip_man, style: style)
# lok_yiu = Practitioner.create(name: "Lok Yiu")
# lok_yiu.disciple_of!(yip_man, style: style)
# jiu_wan = Practitioner.create(name: "Jiu Wan")
# jiu_wan.disciple_of!(yip_man, style: style)
# wong_shun_leung = Practitioner.create(name: "Wong Shun Leung")
# wong_shun_leung.disciple_of!(yip_man, style: style)
# ho_kam_ming = Practitioner.create(name: "Ho Kam Ming")
# ho_kam_ming.disciple_of!(yip_man, style: style)
# leung_ting = Practitioner.create(name: "Leung Ting")
# leung_ting.disciple_of!(yip_man, style: style)
